name: Hello World!

on: 
  push:
    branches:
      - master

jobs: 
  hello_world_job:
    runs-on: ubuntu-20.04       
    steps:
      - name: Now it
      - run: |
          echo 'Hello World!'
    steps:
      - name: Not it 2
      - run: echo 'Hello World!2'
  