name: deploy

on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest
    needs: Deployment pipeline
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'test-deploy-githubaction'
          heroku_email: '2751vikassing@gmail.com'